export const EVENTS = {
    ON_DISCONNECT: "disconnecting",
    CALL_END:"CALL_END",
    JOIN_ROOM: "JOIN_ROOM",
    DRAW: "DRAW",
    STOP_DRAWING: "STOP_DRAWING",
    MOUSE_DOWN: "MOUSE_DOWN",
    MOUSE_MOVE: "MOUSE_MOVE",
    MOUSE_UP: "MOUSE_UP",
    MOUSE_OUT: "MOUSE_OUT",
    EMIT_DRAWING_CORDS: "EMIT_DRAWING_CORDS",
    EMIT_STOP_DRAWING: "EMIT_STOP_DRAWING",
    EMIT_CLEAR_CANVAS: "EMIT_CLEAR_CANVAS",
    ON_CLEAR_CANVAS: "ON_CLEAR_CANVAS",
    EMIT_UNDO: "EMIT_UNDO",
    ON_UNDO: "ON_UNDO",
    ON_VIDEO_SELECT: "ON_VIDEO_SELECT",
    ON_VIDEO_SHOW: "ON_VIDEO_SHOW",
    ON_VIDEO_PLAY_PAUSE: "ON_VIDEO_PLAY_PAUSE",
    ON_VIDEO_TIME: "ON_VIDEO_TIME",
    TOGGLE_DRAWING_MODE:"TOGGLE_DRAWING_MODE",
    TOGGLE_FULL_SCREEN:"TOGGLE_FULL_SCREEN",
    VIDEO_CALL: {
        ON_OFFER: "offer",
        ON_SIGNAL: "signal",
        ON_ANSWER: "answer",
        ON_ICE_CANDIDATE: "ice-candidate",
        ON_STREAM: "stream",
        ON_CONNECT: "connect",
        ON_CLOSE: "close",
        MUTE_ME: "MUTE_ME",
        STOP_FEED: "STOP_FEED"
    },
    TOGGLE_LOCK_MODE:"TOGGLE_LOCK_MODE",
    PUSH_NOTIFICATIONS : {
        ON_SEND : 'send',
        ON_RECEIVE : 'receive'
    },
    ON_VIDEO_ZOOM_PAN:"ON_VIDEO_ZOOM_PAN",
    INSTANT_LESSON: {
        REQUEST: "INSTANT_LESSON_REQUEST",
        ACCEPT: "INSTANT_LESSON_ACCEPT",
        DECLINE: "INSTANT_LESSON_DECLINE",
        EXPIRE: "INSTANT_LESSON_EXPIRE"
    }
}